/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     Action
    /// </summary>
    [JsonConverter(typeof(ActionJsonConverter))]
    [DataContract(Name = "Action")]
    public class Action : AbstractOpenAPISchema
    {
        private object _actualInstance;

        /// <summary>
        ///     Initializes a new instance of the <see cref="Action" /> class
        ///     with the <see cref="TransactionAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of TransactionAction.</param>
        public Action(TransactionAction actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="Action" /> class
        ///     with the <see cref="SignableAction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SignableAction.</param>
        public Action(SignableAction actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Gets or Sets ActualInstance
        /// </summary>
        public override object ActualInstance
        {
            get => _actualInstance;
            set
            {
                if (value.GetType() == typeof(SignableAction) || value is SignableAction)
                    _actualInstance = value;
                else if (value.GetType() == typeof(TransactionAction) || value is TransactionAction)
                    _actualInstance = value;
                else
                    throw new ArgumentException(
                        "Invalid instance found. Must be the following types: SignableAction, TransactionAction");
            }
        }

        /// <summary>
        ///     Get the actual instance of `TransactionAction`. If the actual instance is not `TransactionAction`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of TransactionAction</returns>
        public TransactionAction GetTransactionAction()
        {
            return (TransactionAction)ActualInstance;
        }

        /// <summary>
        ///     Get the actual instance of `SignableAction`. If the actual instance is not `SignableAction`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SignableAction</returns>
        public SignableAction GetSignableAction()
        {
            return (SignableAction)ActualInstance;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Action {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, SerializerSettings);
        }

        /// <summary>
        ///     Converts the JSON string into an instance of Action
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of Action</returns>
        public static Action FromJson(string jsonString)
        {
            Action newAction = null;

            if (string.IsNullOrEmpty(jsonString)) return newAction;
            var match = 0;
            var matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SignableAction).GetProperty("AdditionalProperties") == null)
                    newAction = new Action(
                        JsonConvert.DeserializeObject<SignableAction>(jsonString, SerializerSettings));
                else
                    newAction = new Action(JsonConvert.DeserializeObject<SignableAction>(jsonString,
                        AdditionalPropertiesSerializerSettings));
                matchedTypes.Add("SignableAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into SignableAction: {1}", jsonString, exception);
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(TransactionAction).GetProperty("AdditionalProperties") == null)
                    newAction = new Action(
                        JsonConvert.DeserializeObject<TransactionAction>(jsonString, SerializerSettings));
                else
                    newAction = new Action(JsonConvert.DeserializeObject<TransactionAction>(jsonString,
                        AdditionalPropertiesSerializerSettings));
                matchedTypes.Add("TransactionAction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into TransactionAction: {1}", jsonString, exception);
            }

            if (match == 0)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` cannot be deserialized into any schema defined.");
            if (match > 1)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` incorrectly matches more than one schema (should be exactly one match): " +
                                               string.Join(",", matchedTypes));

            // deserialization is considered successful at this point if no exception has been thrown.
            return newAction;
        }
    }

    /// <summary>
    ///     Custom JSON converter for Action
    /// </summary>
    public class ActionJsonConverter : JsonConverter
    {
        /// <summary>
        ///     To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)typeof(Action).GetMethod("ToJson").Invoke(value, null));
        }

        /// <summary>
        ///     To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue,
            JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.StartObject:
                    return Action.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return Action.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        ///     Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }
}