/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     CancelOrders200ResponseResult
    /// </summary>
    [DataContract(Name = "cancelOrders_200_response_result")]
    public class CancelOrders200ResponseResult
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="CancelOrders200ResponseResult" /> class.
        /// </summary>
        /// <param name="failedCancellations">Orders which failed to be cancelled.</param>
        /// <param name="pendingCancellations">Orders which are marked for cancellation but the cancellation cannot be guaranteed.</param>
        /// <param name="successfulCancellations">Orders which were successfully cancelled.</param>
        public CancelOrders200ResponseResult(
            List<CancelOrders200ResponseResultFailedCancellationsInner> failedCancellations = default,
            List<string> pendingCancellations = default, List<string> successfulCancellations = default)
        {
            FailedCancellations = failedCancellations;
            PendingCancellations = pendingCancellations;
            SuccessfulCancellations = successfulCancellations;
        }

        /// <summary>
        ///     Orders which failed to be cancelled
        /// </summary>
        /// <value>Orders which failed to be cancelled</value>
        [DataMember(Name = "failed_cancellations", EmitDefaultValue = false)]
        public List<CancelOrders200ResponseResultFailedCancellationsInner> FailedCancellations { get; set; }

        /// <summary>
        ///     Orders which are marked for cancellation but the cancellation cannot be guaranteed
        /// </summary>
        /// <value>Orders which are marked for cancellation but the cancellation cannot be guaranteed</value>
        [DataMember(Name = "pending_cancellations", EmitDefaultValue = false)]
        public List<string> PendingCancellations { get; set; }

        /// <summary>
        ///     Orders which were successfully cancelled
        /// </summary>
        /// <value>Orders which were successfully cancelled</value>
        [DataMember(Name = "successful_cancellations", EmitDefaultValue = false)]
        public List<string> SuccessfulCancellations { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CancelOrders200ResponseResult {\n");
            sb.Append("  FailedCancellations: ").Append(FailedCancellations).Append("\n");
            sb.Append("  PendingCancellations: ").Append(PendingCancellations).Append("\n");
            sb.Append("  SuccessfulCancellations: ").Append(SuccessfulCancellations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}