/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     Whether the cancellation was done on-chain or off-chain or as a result of an underfunded account
    /// </summary>
    /// <value>Whether the cancellation was done on-chain or off-chain or as a result of an underfunded account</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CancelledOrderStatusCancellationType
    {
        /// <summary>
        ///     Enum ONCHAIN for value: ON_CHAIN
        /// </summary>
        [EnumMember(Value = "ON_CHAIN")] ONCHAIN,

        /// <summary>
        ///     Enum OFFCHAIN for value: OFF_CHAIN
        /// </summary>
        [EnumMember(Value = "OFF_CHAIN")] OFFCHAIN,

        /// <summary>
        ///     Enum UNDERFUNDED for value: UNDERFUNDED
        /// </summary>
        [EnumMember(Value = "UNDERFUNDED")] UNDERFUNDED
    }
}