/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     Fee
    /// </summary>
    [DataContract(Name = "Fee")]
    public class Fee
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="Fee" /> class.
        /// </summary>
        /// <param name="amount">amount.</param>
        /// <param name="recipientAddress">recipientAddress.</param>
        /// <param name="type">type.</param>
        public Fee(string amount = default, string recipientAddress = default, FeeType? type = default)
        {
            Amount = amount;
            RecipientAddress = recipientAddress;
            Type = type;
        }

        /// <summary>
        ///     Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public FeeType? Type { get; set; }

        /// <summary>
        ///     Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", EmitDefaultValue = false)]
        public string Amount { get; set; }

        /// <summary>
        ///     Gets or Sets RecipientAddress
        /// </summary>
        [DataMember(Name = "recipientAddress", EmitDefaultValue = false)]
        public string RecipientAddress { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Fee {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  RecipientAddress: ").Append(RecipientAddress).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}