/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     FeeValue
    /// </summary>
    [DataContract(Name = "FeeValue")]
    public class FeeValue
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="FeeValue" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeeValue()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="FeeValue" /> class.
        /// </summary>
        /// <param name="amount">amount (required).</param>
        /// <param name="recipientAddress">recipientAddress (required).</param>
        public FeeValue(string amount = default, string recipientAddress = default)
        {
            // to ensure "amount" is required (not null)
            if (amount == null)
                throw new ArgumentNullException("amount is a required property for FeeValue and cannot be null");
            Amount = amount;
            // to ensure "recipientAddress" is required (not null)
            if (recipientAddress == null)
                throw new ArgumentNullException(
                    "recipientAddress is a required property for FeeValue and cannot be null");
            RecipientAddress = recipientAddress;
        }

        /// <summary>
        ///     Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        ///     Gets or Sets RecipientAddress
        /// </summary>
        [DataMember(Name = "recipientAddress", IsRequired = true, EmitDefaultValue = true)]
        public string RecipientAddress { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FeeValue {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  RecipientAddress: ").Append(RecipientAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}