/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     Defines ItemType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ItemType
    {
        /// <summary>
        ///     Enum _0 for value: 0
        /// </summary>
        [EnumMember(Value = "0")] _0,

        /// <summary>
        ///     Enum _1 for value: 1
        /// </summary>
        [EnumMember(Value = "1")] _1,

        /// <summary>
        ///     Enum _2 for value: 2
        /// </summary>
        [EnumMember(Value = "2")] _2,

        /// <summary>
        ///     Enum _3 for value: 3
        /// </summary>
        [EnumMember(Value = "3")] _3,

        /// <summary>
        ///     Enum _4 for value: 4
        /// </summary>
        [EnumMember(Value = "4")] _4,

        /// <summary>
        ///     Enum _5 for value: 5
        /// </summary>
        [EnumMember(Value = "5")] _5
    }
}