/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     OrderStatusOneOf4
    /// </summary>
    [DataContract(Name = "OrderStatus_oneOf_4")]
    public class OrderStatusOneOf4
    {
        /// <summary>
        ///     The order status that indicates an order cannot be fulfilled.
        /// </summary>
        /// <value>The order status that indicates an order cannot be fulfilled.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum NameEnum
        {
            /// <summary>
            ///     Enum INACTIVE for value: INACTIVE
            /// </summary>
            [EnumMember(Value = "INACTIVE")] INACTIVE
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="OrderStatusOneOf4" /> class.
        /// </summary>
        /// <param name="name">The order status that indicates an order cannot be fulfilled..</param>
        /// <param name="sufficientApprovals">Whether the order offerer has sufficient approvals.</param>
        /// <param name="sufficientBalances">Whether the order offerer still has sufficient balance to complete the order.</param>
        public OrderStatusOneOf4(NameEnum? name = default, bool sufficientApprovals = default,
            bool sufficientBalances = default)
        {
            Name = name;
            SufficientApprovals = sufficientApprovals;
            SufficientBalances = sufficientBalances;
        }


        /// <summary>
        ///     The order status that indicates an order cannot be fulfilled.
        /// </summary>
        /// <value>The order status that indicates an order cannot be fulfilled.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public NameEnum? Name { get; set; }

        /// <summary>
        ///     Whether the order offerer has sufficient approvals
        /// </summary>
        /// <value>Whether the order offerer has sufficient approvals</value>
        [DataMember(Name = "sufficient_approvals", EmitDefaultValue = true)]
        public bool SufficientApprovals { get; set; }

        /// <summary>
        ///     Whether the order offerer still has sufficient balance to complete the order
        /// </summary>
        /// <value>Whether the order offerer still has sufficient balance to complete the order</value>
        [DataMember(Name = "sufficient_balances", EmitDefaultValue = true)]
        public bool SufficientBalances { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderStatusOneOf4 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SufficientApprovals: ").Append(SufficientApprovals).Append("\n");
            sb.Append("  SufficientBalances: ").Append(SufficientBalances).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}