/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     Defines SignablePurpose
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SignablePurpose
    {
        /// <summary>
        ///     Enum CREATELISTING for value: CREATE_LISTING
        /// </summary>
        [EnumMember(Value = "CREATE_LISTING")] CREATELISTING,

        /// <summary>
        ///     Enum OFFCHAINCANCELLATION for value: OFF_CHAIN_CANCELLATION
        /// </summary>
        [EnumMember(Value = "OFF_CHAIN_CANCELLATION")]
        OFFCHAINCANCELLATION
    }
}