/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     Defines TransactionPurpose
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionPurpose
    {
        /// <summary>
        ///     Enum APPROVAL for value: APPROVAL
        /// </summary>
        [EnumMember(Value = "APPROVAL")] APPROVAL,

        /// <summary>
        ///     Enum FULFILLORDER for value: FULFILL_ORDER
        /// </summary>
        [EnumMember(Value = "FULFILL_ORDER")] FULFILLORDER,

        /// <summary>
        ///     Enum CANCEL for value: CANCEL
        /// </summary>
        [EnumMember(Value = "CANCEL")] CANCEL
    }
}