/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Immutable.Orderbook.Model
{
    /// <summary>
    ///     TransactionAction
    /// </summary>
    [DataContract(Name = "TransactionAction")]
    public class TransactionAction
    {
        /// <summary>
        ///     Defines Type
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            ///     Enum TRANSACTION for value: TRANSACTION
            /// </summary>
            [EnumMember(Value = "TRANSACTION")] TRANSACTION
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="TransactionAction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionAction()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="TransactionAction" /> class.
        /// </summary>
        /// <param name="populatedTransactions">populatedTransactions.</param>
        /// <param name="purpose">purpose.</param>
        /// <param name="type">type (required).</param>
        public TransactionAction(TransactionActionPopulatedTransactions populatedTransactions = default,
            TransactionPurpose? purpose = default, TypeEnum type = default)
        {
            Type = type;
            PopulatedTransactions = populatedTransactions;
            Purpose = purpose;
        }

        /// <summary>
        ///     Gets or Sets Purpose
        /// </summary>
        [DataMember(Name = "purpose", EmitDefaultValue = false)]
        public TransactionPurpose? Purpose { get; set; }


        /// <summary>
        ///     Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }

        /// <summary>
        ///     Gets or Sets PopulatedTransactions
        /// </summary>
        [DataMember(Name = "populatedTransactions", EmitDefaultValue = false)]
        public TransactionActionPopulatedTransactions PopulatedTransactions { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionAction {\n");
            sb.Append("  PopulatedTransactions: ").Append(PopulatedTransactions).Append("\n");
            sb.Append("  Purpose: ").Append(Purpose).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}