/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// ActivityNativeToken
    /// </summary>
    [DataContract(Name = "ActivityNativeToken")]
    public partial class ActivityNativeToken
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityNativeToken" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActivityNativeToken() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityNativeToken" /> class.
        /// </summary>
        /// <param name="symbol">The token symbol (required).</param>
        public ActivityNativeToken(string symbol = default(string))
        {
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new ArgumentNullException("symbol is a required property for ActivityNativeToken and cannot be null");
            }
            this.Symbol = symbol;
        }

        /// <summary>
        /// The token symbol
        /// </summary>
        /// <value>The token symbol</value>
        /// <example>ETH</example>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public string Symbol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActivityNativeToken {\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
