/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// FeedItemSocialQuest
    /// </summary>
    [DataContract(Name = "FeedItemSocialQuest")]
    public partial class FeedItemSocialQuest
    {
        /// <summary>
        /// Feed item type
        /// </summary>
        /// <value>Feed item type</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Socialquest for value: socialquest
            /// </summary>
            [EnumMember(Value = "socialquest")]
            Socialquest = 1
        }


        /// <summary>
        /// Feed item type
        /// </summary>
        /// <value>Feed item type</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedItemSocialQuest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeedItemSocialQuest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedItemSocialQuest" /> class.
        /// </summary>
        /// <param name="id">Feed item ID (required).</param>
        /// <param name="name">Feed item name (required).</param>
        /// <param name="questId">Quest ID (required).</param>
        /// <param name="priority">Feed item priority (required).</param>
        /// <param name="gemsEarnable">Amount of gems earnable when user completes the quest (required).</param>
        /// <param name="bypass">If the quest is bypassed, the user will not be able to see it on the feed.</param>
        /// <param name="dayZero">If the quest is a day0 quest.</param>
        /// <param name="gameId">Game ID.</param>
        /// <param name="gameName">Game name.</param>
        /// <param name="questCompletedPopupText">Text to display when the quest is completed in an onboarding experience.</param>
        /// <param name="tags">The tags for the feed item.</param>
        /// <param name="controlTags">Some specific tags for controlling feed items.</param>
        /// <param name="categories">The categories for the feed item.</param>
        /// <param name="onboardingExperience">The onboarding experience for the feed item.</param>
        /// <param name="type">Feed item type (required).</param>
        /// <param name="title">Title of the social quest (required).</param>
        /// <param name="subtitle">Title of the social quest (required).</param>
        /// <param name="label">The label for the CTA button (required).</param>
        /// <param name="description">The description for the CTA button (required).</param>
        /// <param name="url">The URL for the CTA button (required).</param>
        /// <param name="logo">URL of the logo (required).</param>
        /// <param name="platformName">The name of the platform social quest belongs to (required).</param>
        public FeedItemSocialQuest(string id = default(string), string name = default(string), string questId = default(string), int priority = default(int), int gemsEarnable = default(int), bool bypass = default(bool), bool dayZero = default(bool), Guid gameId = default(Guid), string gameName = default(string), string questCompletedPopupText = default(string), List<string> tags = default(List<string>), List<string> controlTags = default(List<string>), List<string> categories = default(List<string>), string onboardingExperience = default(string), TypeEnum type = default(TypeEnum), string title = default(string), string subtitle = default(string), string label = default(string), string description = default(string), string url = default(string), string logo = default(string), string platformName = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Name = name;
            // to ensure "questId" is required (not null)
            if (questId == null)
            {
                throw new ArgumentNullException("questId is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.QuestId = questId;
            this.Priority = priority;
            this.GemsEarnable = gemsEarnable;
            this.Type = type;
            // to ensure "title" is required (not null)
            if (title == null)
            {
                throw new ArgumentNullException("title is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Title = title;
            // to ensure "subtitle" is required (not null)
            if (subtitle == null)
            {
                throw new ArgumentNullException("subtitle is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Subtitle = subtitle;
            // to ensure "label" is required (not null)
            if (label == null)
            {
                throw new ArgumentNullException("label is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Label = label;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Description = description;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Url = url;
            // to ensure "logo" is required (not null)
            if (logo == null)
            {
                throw new ArgumentNullException("logo is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.Logo = logo;
            // to ensure "platformName" is required (not null)
            if (platformName == null)
            {
                throw new ArgumentNullException("platformName is a required property for FeedItemSocialQuest and cannot be null");
            }
            this.PlatformName = platformName;
            this.Bypass = bypass;
            this.DayZero = dayZero;
            this.GameId = gameId;
            this.GameName = gameName;
            this.QuestCompletedPopupText = questCompletedPopupText;
            this.Tags = tags;
            this.ControlTags = controlTags;
            this.Categories = categories;
            this.OnboardingExperience = onboardingExperience;
        }

        /// <summary>
        /// Feed item ID
        /// </summary>
        /// <value>Feed item ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Feed item name
        /// </summary>
        /// <value>Feed item name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Quest ID
        /// </summary>
        /// <value>Quest ID</value>
        [DataMember(Name = "quest_id", IsRequired = true, EmitDefaultValue = true)]
        public string QuestId { get; set; }

        /// <summary>
        /// Feed item priority
        /// </summary>
        /// <value>Feed item priority</value>
        [DataMember(Name = "priority", IsRequired = true, EmitDefaultValue = true)]
        public int Priority { get; set; }

        /// <summary>
        /// Amount of gems earnable when user completes the quest
        /// </summary>
        /// <value>Amount of gems earnable when user completes the quest</value>
        [DataMember(Name = "gems_earnable", IsRequired = true, EmitDefaultValue = true)]
        public int GemsEarnable { get; set; }

        /// <summary>
        /// If the quest is bypassed, the user will not be able to see it on the feed
        /// </summary>
        /// <value>If the quest is bypassed, the user will not be able to see it on the feed</value>
        [DataMember(Name = "bypass", EmitDefaultValue = true)]
        public bool Bypass { get; set; }

        /// <summary>
        /// If the quest is a day0 quest
        /// </summary>
        /// <value>If the quest is a day0 quest</value>
        [DataMember(Name = "day_zero", EmitDefaultValue = true)]
        public bool DayZero { get; set; }

        /// <summary>
        /// Game ID
        /// </summary>
        /// <value>Game ID</value>
        [DataMember(Name = "game_id", EmitDefaultValue = false)]
        public Guid GameId { get; set; }

        /// <summary>
        /// Game name
        /// </summary>
        /// <value>Game name</value>
        [DataMember(Name = "game_name", EmitDefaultValue = false)]
        public string GameName { get; set; }

        /// <summary>
        /// Text to display when the quest is completed in an onboarding experience
        /// </summary>
        /// <value>Text to display when the quest is completed in an onboarding experience</value>
        [DataMember(Name = "quest_completed_popup_text", EmitDefaultValue = false)]
        public string QuestCompletedPopupText { get; set; }

        /// <summary>
        /// The tags for the feed item
        /// </summary>
        /// <value>The tags for the feed item</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Some specific tags for controlling feed items
        /// </summary>
        /// <value>Some specific tags for controlling feed items</value>
        [DataMember(Name = "control_tags", EmitDefaultValue = false)]
        public List<string> ControlTags { get; set; }

        /// <summary>
        /// The categories for the feed item
        /// </summary>
        /// <value>The categories for the feed item</value>
        [DataMember(Name = "categories", EmitDefaultValue = false)]
        public List<string> Categories { get; set; }

        /// <summary>
        /// The onboarding experience for the feed item
        /// </summary>
        /// <value>The onboarding experience for the feed item</value>
        [DataMember(Name = "onboarding_experience", EmitDefaultValue = false)]
        public string OnboardingExperience { get; set; }

        /// <summary>
        /// Title of the social quest
        /// </summary>
        /// <value>Title of the social quest</value>
        [DataMember(Name = "title", IsRequired = true, EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// Title of the social quest
        /// </summary>
        /// <value>Title of the social quest</value>
        [DataMember(Name = "subtitle", IsRequired = true, EmitDefaultValue = true)]
        public string Subtitle { get; set; }

        /// <summary>
        /// The label for the CTA button
        /// </summary>
        /// <value>The label for the CTA button</value>
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// The description for the CTA button
        /// </summary>
        /// <value>The description for the CTA button</value>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// The URL for the CTA button
        /// </summary>
        /// <value>The URL for the CTA button</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// URL of the logo
        /// </summary>
        /// <value>URL of the logo</value>
        [DataMember(Name = "logo", IsRequired = true, EmitDefaultValue = true)]
        public string Logo { get; set; }

        /// <summary>
        /// The name of the platform social quest belongs to
        /// </summary>
        /// <value>The name of the platform social quest belongs to</value>
        [DataMember(Name = "platform_name", IsRequired = true, EmitDefaultValue = true)]
        public string PlatformName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeedItemSocialQuest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  QuestId: ").Append(QuestId).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  GemsEarnable: ").Append(GemsEarnable).Append("\n");
            sb.Append("  Bypass: ").Append(Bypass).Append("\n");
            sb.Append("  DayZero: ").Append(DayZero).Append("\n");
            sb.Append("  GameId: ").Append(GameId).Append("\n");
            sb.Append("  GameName: ").Append(GameName).Append("\n");
            sb.Append("  QuestCompletedPopupText: ").Append(QuestCompletedPopupText).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  ControlTags: ").Append(ControlTags).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  OnboardingExperience: ").Append(OnboardingExperience).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Subtitle: ").Append(Subtitle).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("  PlatformName: ").Append(PlatformName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
