/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// FeedItemQuiz
    /// </summary>
    [DataContract(Name = "FeedItemQuiz")]
    public partial class FeedItemQuiz
    {
        /// <summary>
        /// Feed item type
        /// </summary>
        /// <value>Feed item type</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Quiz for value: quiz
            /// </summary>
            [EnumMember(Value = "quiz")]
            Quiz = 1
        }


        /// <summary>
        /// Feed item type
        /// </summary>
        /// <value>Feed item type</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedItemQuiz" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FeedItemQuiz() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FeedItemQuiz" /> class.
        /// </summary>
        /// <param name="id">Feed item ID (required).</param>
        /// <param name="name">Feed item name (required).</param>
        /// <param name="questId">Quest ID (required).</param>
        /// <param name="priority">Feed item priority (required).</param>
        /// <param name="gemsEarnable">Amount of gems earnable when user completes the quest (required).</param>
        /// <param name="bypass">If the quest is bypassed, the user will not be able to see it on the feed.</param>
        /// <param name="dayZero">If the quest is a day0 quest.</param>
        /// <param name="gameId">Game ID.</param>
        /// <param name="gameName">Game name.</param>
        /// <param name="questCompletedPopupText">Text to display when the quest is completed in an onboarding experience.</param>
        /// <param name="tags">The tags for the feed item.</param>
        /// <param name="categories">The categories for the feed item.</param>
        /// <param name="onboardingExperience">The onboarding experience for the feed item.</param>
        /// <param name="type">Feed item type (required).</param>
        /// <param name="headerVideoUrl">URL of the quiz header video.</param>
        /// <param name="logo">URL of the quiz logo.</param>
        /// <param name="question">The quiz question (required).</param>
        /// <param name="answers">Quiz answers to display (required).</param>
        /// <param name="correctAnswers">Quiz correct answers (required).</param>
        /// <param name="correctAnswerText">The text to display when the user answers the quiz correctly.</param>
        /// <param name="headerInitialImage">The initial image for the quiz header.</param>
        /// <param name="headerAnsweredImage">The image to display when the user answers the quiz correctly.</param>
        public FeedItemQuiz(string id = default(string), string name = default(string), string questId = default(string), int priority = default(int), int gemsEarnable = default(int), bool bypass = default(bool), bool dayZero = default(bool), Guid gameId = default(Guid), string gameName = default(string), string questCompletedPopupText = default(string), List<string> tags = default(List<string>), List<string> categories = default(List<string>), string onboardingExperience = default(string), TypeEnum type = default(TypeEnum), string headerVideoUrl = default(string), string logo = default(string), string question = default(string), List<string> answers = default(List<string>), List<int> correctAnswers = default(List<int>), string correctAnswerText = default(string), string headerInitialImage = default(string), string headerAnsweredImage = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for FeedItemQuiz and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for FeedItemQuiz and cannot be null");
            }
            this.Name = name;
            // to ensure "questId" is required (not null)
            if (questId == null)
            {
                throw new ArgumentNullException("questId is a required property for FeedItemQuiz and cannot be null");
            }
            this.QuestId = questId;
            this.Priority = priority;
            this.GemsEarnable = gemsEarnable;
            this.Type = type;
            // to ensure "question" is required (not null)
            if (question == null)
            {
                throw new ArgumentNullException("question is a required property for FeedItemQuiz and cannot be null");
            }
            this.Question = question;
            // to ensure "answers" is required (not null)
            if (answers == null)
            {
                throw new ArgumentNullException("answers is a required property for FeedItemQuiz and cannot be null");
            }
            this.Answers = answers;
            // to ensure "correctAnswers" is required (not null)
            if (correctAnswers == null)
            {
                throw new ArgumentNullException("correctAnswers is a required property for FeedItemQuiz and cannot be null");
            }
            this.CorrectAnswers = correctAnswers;
            this.Bypass = bypass;
            this.DayZero = dayZero;
            this.GameId = gameId;
            this.GameName = gameName;
            this.QuestCompletedPopupText = questCompletedPopupText;
            this.Tags = tags;
            this.Categories = categories;
            this.OnboardingExperience = onboardingExperience;
            this.HeaderVideoUrl = headerVideoUrl;
            this.Logo = logo;
            this.CorrectAnswerText = correctAnswerText;
            this.HeaderInitialImage = headerInitialImage;
            this.HeaderAnsweredImage = headerAnsweredImage;
        }

        /// <summary>
        /// Feed item ID
        /// </summary>
        /// <value>Feed item ID</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Feed item name
        /// </summary>
        /// <value>Feed item name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Quest ID
        /// </summary>
        /// <value>Quest ID</value>
        [DataMember(Name = "quest_id", IsRequired = true, EmitDefaultValue = true)]
        public string QuestId { get; set; }

        /// <summary>
        /// Feed item priority
        /// </summary>
        /// <value>Feed item priority</value>
        [DataMember(Name = "priority", IsRequired = true, EmitDefaultValue = true)]
        public int Priority { get; set; }

        /// <summary>
        /// Amount of gems earnable when user completes the quest
        /// </summary>
        /// <value>Amount of gems earnable when user completes the quest</value>
        [DataMember(Name = "gems_earnable", IsRequired = true, EmitDefaultValue = true)]
        public int GemsEarnable { get; set; }

        /// <summary>
        /// If the quest is bypassed, the user will not be able to see it on the feed
        /// </summary>
        /// <value>If the quest is bypassed, the user will not be able to see it on the feed</value>
        [DataMember(Name = "bypass", EmitDefaultValue = true)]
        public bool Bypass { get; set; }

        /// <summary>
        /// If the quest is a day0 quest
        /// </summary>
        /// <value>If the quest is a day0 quest</value>
        [DataMember(Name = "day_zero", EmitDefaultValue = true)]
        public bool DayZero { get; set; }

        /// <summary>
        /// Game ID
        /// </summary>
        /// <value>Game ID</value>
        [DataMember(Name = "game_id", EmitDefaultValue = false)]
        public Guid GameId { get; set; }

        /// <summary>
        /// Game name
        /// </summary>
        /// <value>Game name</value>
        [DataMember(Name = "game_name", EmitDefaultValue = false)]
        public string GameName { get; set; }

        /// <summary>
        /// Text to display when the quest is completed in an onboarding experience
        /// </summary>
        /// <value>Text to display when the quest is completed in an onboarding experience</value>
        [DataMember(Name = "quest_completed_popup_text", EmitDefaultValue = false)]
        public string QuestCompletedPopupText { get; set; }

        /// <summary>
        /// The tags for the feed item
        /// </summary>
        /// <value>The tags for the feed item</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// The categories for the feed item
        /// </summary>
        /// <value>The categories for the feed item</value>
        [DataMember(Name = "categories", EmitDefaultValue = false)]
        public List<string> Categories { get; set; }

        /// <summary>
        /// The onboarding experience for the feed item
        /// </summary>
        /// <value>The onboarding experience for the feed item</value>
        [DataMember(Name = "onboarding_experience", EmitDefaultValue = false)]
        public string OnboardingExperience { get; set; }

        /// <summary>
        /// URL of the quiz header video
        /// </summary>
        /// <value>URL of the quiz header video</value>
        [DataMember(Name = "header_video_url", EmitDefaultValue = false)]
        public string HeaderVideoUrl { get; set; }

        /// <summary>
        /// URL of the quiz logo
        /// </summary>
        /// <value>URL of the quiz logo</value>
        [DataMember(Name = "logo", EmitDefaultValue = false)]
        public string Logo { get; set; }

        /// <summary>
        /// The quiz question
        /// </summary>
        /// <value>The quiz question</value>
        [DataMember(Name = "question", IsRequired = true, EmitDefaultValue = true)]
        public string Question { get; set; }

        /// <summary>
        /// Quiz answers to display
        /// </summary>
        /// <value>Quiz answers to display</value>
        [DataMember(Name = "answers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Answers { get; set; }

        /// <summary>
        /// Quiz correct answers
        /// </summary>
        /// <value>Quiz correct answers</value>
        [DataMember(Name = "correct_answers", IsRequired = true, EmitDefaultValue = true)]
        public List<int> CorrectAnswers { get; set; }

        /// <summary>
        /// The text to display when the user answers the quiz correctly
        /// </summary>
        /// <value>The text to display when the user answers the quiz correctly</value>
        [DataMember(Name = "correct_answer_text", EmitDefaultValue = false)]
        public string CorrectAnswerText { get; set; }

        /// <summary>
        /// The initial image for the quiz header
        /// </summary>
        /// <value>The initial image for the quiz header</value>
        [DataMember(Name = "header_initial_image", EmitDefaultValue = false)]
        public string HeaderInitialImage { get; set; }

        /// <summary>
        /// The image to display when the user answers the quiz correctly
        /// </summary>
        /// <value>The image to display when the user answers the quiz correctly</value>
        [DataMember(Name = "header_answered_image", EmitDefaultValue = false)]
        public string HeaderAnsweredImage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FeedItemQuiz {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  QuestId: ").Append(QuestId).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  GemsEarnable: ").Append(GemsEarnable).Append("\n");
            sb.Append("  Bypass: ").Append(Bypass).Append("\n");
            sb.Append("  DayZero: ").Append(DayZero).Append("\n");
            sb.Append("  GameId: ").Append(GameId).Append("\n");
            sb.Append("  GameName: ").Append(GameName).Append("\n");
            sb.Append("  QuestCompletedPopupText: ").Append(QuestCompletedPopupText).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Categories: ").Append(Categories).Append("\n");
            sb.Append("  OnboardingExperience: ").Append(OnboardingExperience).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  HeaderVideoUrl: ").Append(HeaderVideoUrl).Append("\n");
            sb.Append("  Logo: ").Append(Logo).Append("\n");
            sb.Append("  Question: ").Append(Question).Append("\n");
            sb.Append("  Answers: ").Append(Answers).Append("\n");
            sb.Append("  CorrectAnswers: ").Append(CorrectAnswers).Append("\n");
            sb.Append("  CorrectAnswerText: ").Append(CorrectAnswerText).Append("\n");
            sb.Append("  HeaderInitialImage: ").Append(HeaderInitialImage).Append("\n");
            sb.Append("  HeaderAnsweredImage: ").Append(HeaderAnsweredImage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
