/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// MarketPriceNativeToken
    /// </summary>
    [DataContract(Name = "MarketPriceNativeToken")]
    public partial class MarketPriceNativeToken
    {
        /// <summary>
        /// Token type user is offering, which in this case is the native IMX token
        /// </summary>
        /// <value>Token type user is offering, which in this case is the native IMX token</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum NATIVE for value: NATIVE
            /// </summary>
            [EnumMember(Value = "NATIVE")]
            NATIVE = 1
        }


        /// <summary>
        /// Token type user is offering, which in this case is the native IMX token
        /// </summary>
        /// <value>Token type user is offering, which in this case is the native IMX token</value>
        /// <example>NATIVE</example>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketPriceNativeToken" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MarketPriceNativeToken() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketPriceNativeToken" /> class.
        /// </summary>
        /// <param name="type">Token type user is offering, which in this case is the native IMX token (required).</param>
        /// <param name="symbol">The symbol of token (required).</param>
        public MarketPriceNativeToken(TypeEnum type = default(TypeEnum), string symbol = default(string))
        {
            this.Type = type;
            // to ensure "symbol" is required (not null)
            if (symbol == null)
            {
                throw new ArgumentNullException("symbol is a required property for MarketPriceNativeToken and cannot be null");
            }
            this.Symbol = symbol;
        }

        /// <summary>
        /// The symbol of token
        /// </summary>
        /// <value>The symbol of token</value>
        /// <example>IMX</example>
        [DataMember(Name = "symbol", IsRequired = true, EmitDefaultValue = true)]
        public string Symbol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MarketPriceNativeToken {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Symbol: ").Append(Symbol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
