/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// NativeItem
    /// </summary>
    [DataContract(Name = "NativeItem")]
    public partial class NativeItem
    {
        /// <summary>
        /// Token type user is offering, which in this case is the native IMX token
        /// </summary>
        /// <value>Token type user is offering, which in this case is the native IMX token</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum NATIVE for value: NATIVE
            /// </summary>
            [EnumMember(Value = "NATIVE")]
            NATIVE = 1
        }


        /// <summary>
        /// Token type user is offering, which in this case is the native IMX token
        /// </summary>
        /// <value>Token type user is offering, which in this case is the native IMX token</value>
        /// <example>NATIVE</example>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public TypeEnum Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeItem" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NativeItem() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NativeItem" /> class.
        /// </summary>
        /// <param name="type">Token type user is offering, which in this case is the native IMX token (required).</param>
        /// <param name="amount">A string representing the price at which the user is willing to sell the token. This value is provided in the smallest unit of the token (e.g., wei for Ethereum). (required).</param>
        public NativeItem(TypeEnum type = default(TypeEnum), string amount = default(string))
        {
            this.Type = type;
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for NativeItem and cannot be null");
            }
            this.Amount = amount;
        }

        /// <summary>
        /// A string representing the price at which the user is willing to sell the token. This value is provided in the smallest unit of the token (e.g., wei for Ethereum).
        /// </summary>
        /// <value>A string representing the price at which the user is willing to sell the token. This value is provided in the smallest unit of the token (e.g., wei for Ethereum).</value>
        /// <example>9750000000000000000</example>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NativeItem {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
