/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// The update details
    /// </summary>
    [DataContract(Name = "OperatorAllowlistStatusUpdated")]
    public partial class OperatorAllowlistStatusUpdated
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OperatorAllowlistStatusUpdated" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OperatorAllowlistStatusUpdated() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OperatorAllowlistStatusUpdated" /> class.
        /// </summary>
        /// <param name="reason">Why this action was performed (required).</param>
        public OperatorAllowlistStatusUpdated(string reason = default(string))
        {
            // to ensure "reason" is required (not null)
            if (reason == null)
            {
                throw new ArgumentNullException("reason is a required property for OperatorAllowlistStatusUpdated and cannot be null");
            }
            this.Reason = reason;
        }

        /// <summary>
        /// Why this action was performed
        /// </summary>
        /// <value>Why this action was performed</value>
        /// <example>Contract meets expectations</example>
        [DataMember(Name = "reason", IsRequired = true, EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OperatorAllowlistStatusUpdated {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
