/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// The status of a contract on the operator allowlist
    /// </summary>
    /// <value>The status of a contract on the operator allowlist</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OperatorAllowlistStatus
    {
        /// <summary>
        /// Enum Requested for value: requested
        /// </summary>
        [EnumMember(Value = "requested")]
        Requested = 1,

        /// <summary>
        /// Enum Approved for value: approved
        /// </summary>
        [EnumMember(Value = "approved")]
        Approved = 2,

        /// <summary>
        /// Enum Rejected for value: rejected
        /// </summary>
        [EnumMember(Value = "rejected")]
        Rejected = 3,

        /// <summary>
        /// Enum Removed for value: removed
        /// </summary>
        [EnumMember(Value = "removed")]
        Removed = 4,

        /// <summary>
        /// Enum Added for value: added
        /// </summary>
        [EnumMember(Value = "added")]
        Added = 5
    }

}
