/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// Phone number OTP request
    /// </summary>
    [DataContract(Name = "PhoneNumberOTPResponse")]
    public partial class PhoneNumberOTPResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhoneNumberOTPResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PhoneNumberOTPResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PhoneNumberOTPResponse" /> class.
        /// </summary>
        /// <param name="phoneNumber">Phone number (required).</param>
        public PhoneNumberOTPResponse(string phoneNumber = default(string))
        {
            // to ensure "phoneNumber" is required (not null)
            if (phoneNumber == null)
            {
                throw new ArgumentNullException("phoneNumber is a required property for PhoneNumberOTPResponse and cannot be null");
            }
            this.PhoneNumber = phoneNumber;
        }

        /// <summary>
        /// Phone number
        /// </summary>
        /// <value>Phone number</value>
        /// <example>+61412345678</example>
        [DataMember(Name = "phone_number", IsRequired = true, EmitDefaultValue = true)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PhoneNumberOTPResponse {\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
