/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// RefreshCollectionMetadataRequest
    /// </summary>
    [DataContract(Name = "RefreshCollectionMetadataRequest")]
    public partial class RefreshCollectionMetadataRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RefreshCollectionMetadataRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RefreshCollectionMetadataRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RefreshCollectionMetadataRequest" /> class.
        /// </summary>
        /// <param name="collectionMetadata">collectionMetadata (required).</param>
        public RefreshCollectionMetadataRequest(CollectionMetadata collectionMetadata = default(CollectionMetadata))
        {
            // to ensure "collectionMetadata" is required (not null)
            if (collectionMetadata == null)
            {
                throw new ArgumentNullException("collectionMetadata is a required property for RefreshCollectionMetadataRequest and cannot be null");
            }
            this.CollectionMetadata = collectionMetadata;
        }

        /// <summary>
        /// Gets or Sets CollectionMetadata
        /// </summary>
        [DataMember(Name = "collection_metadata", IsRequired = true, EmitDefaultValue = true)]
        public CollectionMetadata CollectionMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RefreshCollectionMetadataRequest {\n");
            sb.Append("  CollectionMetadata: ").Append(CollectionMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
