/*
 * Immutable zkEVM API
 *
 * Immutable Multi Rollup API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Api.ZkEvm.Client.OpenAPIDateConverter;

namespace Immutable.Api.ZkEvm.Model
{
    /// <summary>
    /// FailedOrderCancellation
    /// </summary>
    [DataContract(Name = "FailedOrderCancellation")]
    public partial class FailedOrderCancellation
    {
        /// <summary>
        /// Reason code indicating why the order failed to be cancelled
        /// </summary>
        /// <value>Reason code indicating why the order failed to be cancelled</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReasonCodeEnum
        {
            /// <summary>
            /// Enum FILLED for value: FILLED
            /// </summary>
            [EnumMember(Value = "FILLED")]
            FILLED = 1
        }


        /// <summary>
        /// Reason code indicating why the order failed to be cancelled
        /// </summary>
        /// <value>Reason code indicating why the order failed to be cancelled</value>
        /// <example>FILLED</example>
        [DataMember(Name = "reason_code", IsRequired = true, EmitDefaultValue = true)]
        public ReasonCodeEnum ReasonCode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FailedOrderCancellation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FailedOrderCancellation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FailedOrderCancellation" /> class.
        /// </summary>
        /// <param name="order">ID of the order which failed to be cancelled (required).</param>
        /// <param name="reasonCode">Reason code indicating why the order failed to be cancelled (required).</param>
        public FailedOrderCancellation(string order = default(string), ReasonCodeEnum reasonCode = default(ReasonCodeEnum))
        {
            // to ensure "order" is required (not null)
            if (order == null)
            {
                throw new ArgumentNullException("order is a required property for FailedOrderCancellation and cannot be null");
            }
            this.Order = order;
            this.ReasonCode = reasonCode;
        }

        /// <summary>
        /// ID of the order which failed to be cancelled
        /// </summary>
        /// <value>ID of the order which failed to be cancelled</value>
        /// <example>7df3e99e-f7b3-459c-bef6-ffb66a18bb59</example>
        [DataMember(Name = "order", IsRequired = true, EmitDefaultValue = true)]
        public string Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FailedOrderCancellation {\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  ReasonCode: ").Append(ReasonCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
