name: Publish Passport Tutorials

on:
  # Run when changes are pushed to Passport tutorials or metadata
  push:
    branches:
      - main
    paths:
      - 'sample/Assets/Scripts/Passport/**/tutorial.md'
      - 'sample/Assets/Scripts/Passport/**/metadata.json'
      - 'sample/Assets/Scripts/Passport/features.json'
      - 'sample/Assets/Scripts/Passport/_tutorials~/**/*'

  # Allow manual triggering
  workflow_dispatch:

concurrency:
  group: passport-tutorials
  cancel-in-progress: false

jobs:
  PublishPassportTutorials:
    name: Process and Publish Passport Tutorials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Unity SDK Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Create Parsed Directory
        run: mkdir -p _parsed

      - name: Checkout Docs Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: immutable/docs
          token: ${{ secrets.UNITY_SDK_DOCS_WORKFLOW }}
          path: imx-docs
          ref: 'DVR-295-docs-restructure'

      - name: Setup environment variables
        run: echo "CLONE_DIR=./imx-docs" >> $GITHUB_ENV

      - name: Setup Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Process Passport Tutorials
        run: |
          # Make scripts executable
          chmod +x .github/scripts/aggregate-passport-metadata.js
          chmod +x .github/scripts/process-passport-tutorials.sh
          
          # Generate aggregated JSON file
          node .github/scripts/aggregate-passport-metadata.js
          
          # Process tutorials and copy to docs repo
          .github/scripts/process-passport-tutorials.sh
        shell: bash

      - name: Create Pull Request in Docs Repo
        id: create_pr
        run: |
          cd "$CLONE_DIR"
          if ! git status --porcelain | grep -q .; then
            echo "No changes to commit"
            echo "pr_url=" >> $GITHUB_OUTPUT
            exit 0
          fi

          BRANCH_NAME="chore/sdk-docs-update-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          
          git add .
          git commit -m "Update example app tutorials from SDK repo"
          git push -u origin $BRANCH_NAME
          echo "Successfully pushed changes to docs repo on branch $BRANCH_NAME"

          PR_URL=$(gh pr create \
            --title "Update example app tutorials from SDK repo" \
            --body "Automated PR from unity-immutable-sdk to update tutorials. Review and merge if all looks good." \
            --base DVR-295-docs-restructure \
            --repo immutable/docs)
          
          echo "Successfully created PR in docs repo: $PR_URL"
          echo "pr_url=${PR_URL}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.UNITY_SDK_DOCS_WORKFLOW }}
        shell: bash