---
name: Test

on: [pull_request]

jobs:
  test:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs pull

      - uses: game-ci/unity-test-runner@v3
        id: passportTest
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          unityVersion: 2021.3.26f1
          projectPath: './sample'
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: 'EditMode'
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: ${{ steps.passportTest.outputs.artifactsPath }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results
          path: ${{ steps.passportTest.outputs.coveragePath }}
